### ISSUE TITLE
units as json

### ISSUE THREAD

**Issue by fanatid** [ethereumjs/ethereumjs-units#5]
It will more readable and you don't need disable key spacing for standard in this case

**Comment by axic** [comment]
Actually had it that way at some points, but thought having `JSON.parse()` just to use JSON would be a bit too much. Do you think its worth it?

**Comment by fanatid** [comment]
What do you mean? You don't need `JSON.parse()` for requiring json file -- `require('./units.json')`.

**Comment by axic** [comment]
That's true, I am actually using it elsewhere. The only downside I think is the inability to have proper comments in JSON, otherwise it should be fine.
